[changelog]
header = ""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {% if commit.scope %}**{{ commit.scope }}**: {% endif %}{{ commit.message }} ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/kaviru2/selar-dev/commit/{{ commit.id }}))
{% endfor %}
{% endfor %}
"""
trim = true

[remote.github]
owner = "kaviru2"
repo = "selar-dev"

[git]
conventional_commits = true
filter_unconventional = false
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^perf", group = "Performance" },
  { message = "^refactor", group = "Refactor" },
  { message = "^docs", group = "Documentation" },
  { message = "^chore", group = "Chores" },
  { message = "^ci", group = "CI/CD" },
  { message = "^revert", group = "Reverts" },
]
filter_commits = false
tag_pattern = "v[0-9].*"
